name: CI

on:
  push:
  pull_request:
    branches:
      - '*'
env:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
jobs:
  ci_build:
    name: CI Build
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Nuget Command
        uses: actions/checkout@master
      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
      - run: nuget restore Advanced.DuplicateDetactionAndDeletion/Advanced.D365.sln
